from __future__ import annotations

from datetime import datetime

from jinja2 import Environment, FileSystemLoader, PackageLoader

from daily_briefer.models import DailyBrief


def format_brief(brief: DailyBrief, fmt: str = "markdown") -> str:
    """Format a DailyBrief into a string."""

    if fmt == "markdown":
        return _format_markdown(brief)
    return f"Daily Brief for {brief.master}\nDate: {brief.date:%Y-%m-%d}\n{brief.date:%A}\n\n" + "\n".join(
        f"{item.source}:\n{item.summary}" for item in brief.items
    )


def _format_markdown(brief: DailyBrief) -> str:
    lines: list[str] = []
    lines.append(f"# 📰 Daily Briefing for {brief.master}")
    lines.append("")
    lines.append(f"**{brief.date:%B %d, %Y}** — {brief.date:%A}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for item in brief.items:
        lines.append(f"## {item.source}")
        lines.append("")
        lines.append(f"**Summary:**\n{item.summary}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by DailyBriefer*")
    lines.append("")
    return "\n".join(lines)
