from __future__ import annotations

from datetime import datetime

from jinja2 import Environment, FileSystemLoader, PackageLoader

from daily_briefer.models import DailyBrief


def format_brief(brief: DailyBrief, fmt: str = "markdown") -> str:
    """Format a DailyBrief into a string."""

    if fmt == "markdown":
        return _format_markdown(brief)
    return f"Daily Brief for {brief.master}\nDate: {brief.date:%Y-%m-%d}\n{brief.date:%A}\n\n" + "\n".join(
        f"{item.source}:\n{item.summary}" for item in brief.items
    )


def _format_markdown(brief: DailyBrief) -> str:
    lines: list[str] = []
    lines.append(f"# 📰 Daily Briefing for {brief.master}")
    lines.append("")
    lines.append(f"**{brief.date:%B %d, %Y}** — {brief.date:%A}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for item in brief.items:
        lines.append(f"## {item.source}")
        lines.append("")
        lines.append(f"**Summary:**\n{item.summary}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Generated by DailyBriefer*")
    lines.append("")
    return "\n".join(lines)


def format_brief_html(md_text: str) -> str:
    """Convert Markdown briefing string into styled HTML suitable for email delivery."""
    import markdown

    body_html = markdown.markdown(
        md_text,
        extensions=["tables", "fenced_code", "nl2br"]
    )

    template = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Daily Briefing</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      line-height: 1.6;
      color: #1f2937;
      background-color: #f3f4f6;
      margin: 0;
      padding: 0;
    }}
    .wrapper {{
      max-width: 680px;
      margin: 20px auto;
      background: #ffffff;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    }}
    .header {{
      background: linear-gradient(135deg, #1e3a8a 0%, #3b82f6 100%);
      color: #ffffff;
      padding: 24px 32px;
      text-align: center;
    }}
    .header h1 {{
      margin: 0;
      font-size: 24px;
      font-weight: 700;
      letter-spacing: -0.025em;
    }}
    .content {{
      padding: 32px;
    }}
    .content h1 {{
      font-size: 22px;
      color: #1e3a8a;
      border-bottom: 2px solid #e5e7eb;
      padding-bottom: 8px;
      margin-top: 0;
    }}
    .content h2 {{
      font-size: 18px;
      color: #111827;
      margin-top: 24px;
      margin-bottom: 12px;
    }}
    .content h3 {{
      font-size: 16px;
      color: #374151;
    }}
    .content p {{
      margin-bottom: 16px;
    }}
    .content ul, .content ol {{
      margin-bottom: 20px;
      padding-left: 24px;
    }}
    .content li {{
      margin-bottom: 8px;
    }}
    .content a {{
      color: #2563eb;
      text-decoration: none;
      font-weight: 500;
    }}
    .content a:hover {{
      text-decoration: underline;
    }}
    .content blockquote {{
      background: #eff6ff;
      border-left: 4px solid #3b82f6;
      margin: 16px 0;
      padding: 12px 16px;
      border-radius: 0 8px 8px 0;
    }}
    .content hr {{
      border: 0;
      height: 1px;
      background: #e5e7eb;
      margin: 24px 0;
    }}
    .footer {{
      background: #f9fafb;
      padding: 16px 32px;
      text-align: center;
      font-size: 12px;
      color: #6b7280;
      border-top: 1px solid #e5e7eb;
    }}
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>📰 DailyBriefer Digest</h1>
    </div>
    <div class="content">
      {body_html}
    </div>
    <div class="footer">
      <p>Sent with ❤️ by <strong>DailyBriefer AI</strong> • Reply directly to update your topic preferences or reminders.</p>
    </div>
  </div>
</body>
</html>"""
    return template

